### ISSUE TITLE
Make all .html files more mobile friendly

### ISSUE THREAD

**Issue by Twashi1** [Twashi1/twashi1.github.io#4]
This includes increasing size of the text and hyperlinks because they're too small to click on mobile devices.

**Comment by Twashi1** [comment]
Commit c23d8b02b2864e484adf7311508d75c030d915dd works towards this

**Comment by lucfis** [comment]
Margin (and generally better spacing) made in 6759366 also works towards this, however the changes haven't been made everywhere as it may conflict with the design of some pages

**Comment by Twashi1** [comment]
Copied same margin to PowerPoint page in 47efed1a77cd6ff88093e048246710c3bba73440
